[Back] 유저랭킹기능 구현을 완료했습니다.
sproutt/eussya-eussya-batch pull request #5
Opened 2021-05-01 16:18 UTC by Ilisha29

**구현 내용** : 유저의 모든 ActivityCount를 바탕으로 한 랭킹기능
**구현 결과**
<img width="821" alt="스크린샷 2021-05-02 오전 1 12 18" src="https://user-images.githubusercontent.com/40922963/116788267-9cce5c80-aae3-11eb-942c-8937f8b8682b.png">

- 아직 활동이 없는 회원은 0이라는 값으로 표현(사진에서 O부분)

- ActivityCount가 같은 회원에 대한 랭킹처리 (사진에서 ㅁ부분)
**참고 사항**
- 아직 잔디기능(액티비티)쪽에서 구현이 완료되지 않은거여서 회의에서 진행했던 내용을 바탕으로 구현을 했습니다. 따라서 전체적인 방향이 맞는지에 초점을 맞춰서 리뷰남겨 주신다면 대단히 감사하겠습니다.

2021-05-03 11:56 UTC, dadadamarine commented
lgtm

2021-05-03 11:57 UTC, dadadamarine commented on src/main/java/com/sproutt/eussyaeussyabatch/ranking/MemberActivity.java
> +    private int activityCount;
MemberId는 wapprer, activitiyCount는 primitive 타입인 이유가 있을까요?

2021-05-03 14:11 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyabatch/ranking/MemberActivity.java
> +    private int activityCount;
리팩토링하면서 없앴던 클래스이긴한데 
Wrapper를 사용한 이유는 엔티티작성시 @Id선언할때 Wrapper Long을 사용하기 때문에 맞춰서 구현했었습니다.

2021-05-03 15:13 UTC, hyukjin-lee commented
활동이 없는 회원이 0값을 가지면 정렬할 때 최우선순위가 되어서 골치가 아플 것 같은데 다른 방법을 찾아보면 어떨까요?

2021-05-03 15:29 UTC, hyukjin-lee requested changes

2021-05-03 15:29 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyabatch/entity/MemberRanking.java
> +package com.sproutt.eussyaeussyabatch.entity;
동일 레벨 패키지명이랑 표현 레벨이 다른 것 같습니다
entity, ranking 말고 ranking 의 domain 으로 들어가면 어떨까요

2021-05-03 15:29 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyabatch/ranking/CalculateRankingItemProcessor.java
> +public class CalculateRankingItemProcessor implements ItemProcessor<MemberRanking, MemberRanking> {
RankingItemProcessor 정도로도 충분할 것 같습니다

2021-05-03 15:29 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyabatch/ranking/CalculateRankingItemProcessor.java
> +        executionContext.putInt("beforeActivityCount", 2147483647);
executionContext 를 사용하신 이유가 뭔지 설명해주실 수 있을까요? static 한 상수로도 충분히 사용가능한 것 같아서요

2021-05-03 15:29 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyabatch/entity/MemberRanking.java
> +public class MemberRanking {
보통 Ranking이라고 하면 멤버에 대한 것이 디폴트니까 Ranking 으로 표현해도 좋을 것 같습니다

2021-05-03 15:29 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyabatch/entity/MemberRanking.java
> +    private Long id;
member 의 랭킹으로 알고 있는데 member 와 엮일 fk 는 무엇인가요? 이건 auto generated value 같은데

2021-05-03 15:29 UTC, hyukjin-lee commented on src/main/java/com/sproutt/eussyaeussyabatch/ranking/CalculateRankingItemProcessor.java
> +        executionContext.putLong("index", ++index);
이렇게 세팅해서 어디서 갖다쓰나요?

2021-05-04 10:03 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyabatch/ranking/CalculateRankingItemProcessor.java
> +public class CalculateRankingItemProcessor implements ItemProcessor<MemberRanking, MemberRanking> {
넵 반영했습니다.

2021-05-05 01:11 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyabatch/entity/MemberRanking.java
> +public class MemberRanking {
넵!!

2021-05-05 01:25 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyabatch/entity/MemberRanking.java
> +package com.sproutt.eussyaeussyabatch.entity;
domain을 따로 두는것보다 말씀하신대로 ranking패키지 안에서 관려있는 것들과 함께 관리하는게 더 나은것 같습니다.

2021-05-05 01:30 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyabatch/ranking/CalculateRankingItemProcessor.java
> +        executionContext.putInt("beforeActivityCount", 2147483647);
우선 executionContext를 사용하게된 경위는 스텝이 실행하면서 계속 공유하고 있어야할 자료구조 혹은 변수가 필요했는데.. 지적해주신대로 static으로 처리하는 방법이 있었음에도 기본적인 방법을 왜 생각하지 못했는지 모르겠고 아직 많이 부족하다고 생각했습니다. 보고 부끄러웠습니다..ㅋㅋㅋㅋ

2021-05-05 02:44 UTC, Ilisha29 commented on src/main/java/com/sproutt/eussyaeussyabatch/ranking/CalculateRankingItemProcessor.java
> +        executionContext.putLong("index", ++index);
유저의 랭킹을 계산하는 용도로 사용됩니다!!

2021-05-07 03:49 UTC, Ilisha29 commented
진행한 activity가 없는 회원의 랭킹이 0으로 나오던 문제를 쿼리 수정함으로써 해결 했습니다.
<img width="760" alt="스크린샷 2021-05-07 오후 12 48 32" src="https://user-images.githubusercontent.com/40922963/117395301-9ea87d80-af32-11eb-899b-6288b5776dc5.png">

2021-05-07 04:35 UTC, hyukjin-lee approved these changes

2021-05-07 12:12 UTC, merged